server:
  port: 9007

#---------database ----------------
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user-info
    username: postgres
    password: postgres


## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
