server:
  port: 9007



#===============database======================
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user-info
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create


